---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "default-cluster"
  namespace: "default-namespace"
spec:
  baseDomain: "example.com"
  clusterImageSetNameRef: "default-image:latest"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ..."
  pullSecretRef:
    name: "default-secret"
  clusters:
  - clusterName: "default-cluster"
    extraManifestPath: "/manifests"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "default-manifest.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      environment: "production"
    clusterNetwork:
    - cidr: "10.128.0.0/14"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.0/24"
    apiVIP: "192.168.1.101"
    ingressVIP: "192.168.1.100"
    serviceNetwork:
    - "172.30.0.0/16"
    additionalNTPSources:
    - "pool.ntp.org"
    nodes:
    - hostName: "ahmet"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels:
        role: "master"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sdf"
        size: 500
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0"
            description: "Bond interface 0"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 400
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "eth0"
              destination: "0.0.0.0/0"
              next-hop-address: "192.168.1.1"
    - hostName: "emre"
      role: "master"
      bmcAddress: "172.16.180.19"
      bmcCredentialsName:
        name: "bmc-credentials-1"
      nodeLabels:
        role: "master"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sadas"
        size: 500
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens3f0"
          macAddress: "90:5e:d9:00:0c:6c"
        - name: "ens3f1"
          macAddress: "90:5e:d9:00:0c:6e"
        - name: "ens4f0"
          macAddress: "9c:69:b4:65:6d:a0"
        - name: "ens4f1"
          macAddress: "9c:69:b4:65:6d:a1"
        - name: "ens4f2"
          macAddress: "9c:69:b4:65:6d:a2"
        - name: "ens4f3"
          macAddress: "9c:69:b4:65:6d:a3"
        - name: "ens5f0"
          macAddress: "90:c7:10:01:67:63"
        - name: "ens5f1"
          macAddress: "90:c7:10:01:67:64"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f2"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f3"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond1"
            description: "Bond interface 1"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond1"
              id: 400
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond1.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "eth0"
              destination: "0.0.0.0/0"
              next-hop-address: "192.168.1.1"
