---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "lenovo-ankara-siteconfig"
  namespace: "lenovo"
spec:
  baseDomain: "odine.com"
  clusterImageSetNameRef: "Ubuntu-24-0-1"
  sshPublicKey: "ssh DSFSDLFDKGDFLGSFSD rs"
  pullSecretRef:
    name: "site-config-secret"
  clusters:
  - clusterName: "lenovo-ankara-siteconfig"
    extraManifestPath: "manifests/ManifestWork/"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "ankara-manifestWork.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      label1: "app-ankara"
      label2: "model-netas"
      label3: "domain-anu2cp"
    clusterNetwork:
    - cidr: "10.10.47.12/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "10.10.48.12/24"
    apiVIP: "110.212.144.36"
    ingressVIP: "10.212.144.100"
    serviceNetwork:
    - "10.10.55.30/24"
    - "1"
    additionalNTPSources:
    - "10.10.45.64"
    - "10.225.36.10"
    nodes:
    - hostName: "master1.turkcell.tgc"
      role: "master"
      bmcAddress: "redfish+https://192.168.65.3/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: "bmc-secret-1"
      nodeLabels:
        role: "master"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "Unknown"
        deviceName: "/dev/sda"
        size: 120
      bootMACAddress: "10:10:10:10:10:10"
      nodeNetwork:
        interfaces:
        - name: "ens0f1-10"
          macAddress: "10:10:10:20:10:10:20"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens0f1-10"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0"
            description: "Bond mode for transfer"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 401
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.401"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "bond0.401"
              destination: "0.0.0.0/0"
              next-hop-address: "10.10.50.109"
