---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "mike-cluster-name"
  namespace: "mike-instance-001"
spec:
  baseDomain: "odine-mike.com"
  clusterImageSetNameRef: "Mike Image"
  sshPublicKey: "sdfhjsdkfjsdklfsdhjfk-mike"
  pullSecretRef:
    name: "dlkjfsdljfklsdjfkljdsf-mike"
  clusters:
  - clusterName: "mike-cluster-name"
    extraManifestPath: "Ä±shdjsdhfjhsdkjfhsd-mike"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "mike manifest"
    networkType: "OVNKubernetes"
    clusterLabels: {}
    clusterNetwork:
    - cidr: "192.168.1.0/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.0/24"
    apiVIP: "192.168.1.1"
    ingressVIP: "10.10.10.10"
    serviceNetwork:
    - "mike service 1"
    - "mike service 2"
    - "mike service 3"
    additionalNTPSources:
    - "mike ntp 1"
    - "mike ntp 2"
    nodes:
    - hostName: "mike-hostname"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0-mike"
      nodeLabels:
        openshift-storage: "true"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/mike"
        size: 24
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "balance-xor"
              port:
              - "ens1f1: 04:32:01:52:74:71"
              - "ens1f0: 04:32:01:52:74:70"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "sadasdasd mike"
            description: "dgdfgdfgdfgdfgdfg desc mike"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "sadasdasd mike"
              id: 34
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sadasdasd mike.34"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "192.168.1.1"
          routes:
            config:
            - next-hop-interface: "sdasd"
              destination: "0.0.0.0/0"
              next-hop-address: "10.10.50.129"
    - hostName: "mike-hostanme-2"
      role: "worker"
      bmcAddress: "172.16.180.19"
      bmcCredentialsName:
        name: "bmc-credentials-2-mike"
      nodeLabels: {}
      bootMode: "legacy"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/mike2"
        size: 100
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces: []
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "mikeeeeee"
            description: "mike desc"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "mikeeeeee"
              id: 0
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "mikeeeeee.0"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server: []
          routes:
            config:
            - next-hop-interface: ""
              destination: "0.0.0.0/0"
              next-hop-address: "172.16.180.19"
