---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "prod-test-1"
  namespace: "prod-test"
spec:
  baseDomain: "odine.com.tr"
  clusterImageSetNameRef: "cluster-image-001"
  sshPublicKey: "ssh-rsa DSHFDFHSHYREYDFHERYÊYRRH nova-root"
  pullSecretRef:
    name: "secret/secrets.yaml"
  clusters:
  - clusterName: "prod-test-1"
    extraManifestPath: "/cluıster/policies/"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "policies.yaml"
    networkType: "OVNKubernetes"
    clusterLabels: {}
    clusterNetwork:
    - cidr: "1.1.1.1/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "2.2.2.2/24"
    apiVIP: "4.4.4.4"
    ingressVIP: "3.3.3.3"
    serviceNetwork:
    - "3.4.6.7"
    additionalNTPSources:
    - "10.10.10.10"
    nodes:
    - hostName: "turkcell.host.com"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels: {}
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "Unknown"
        deviceName: "/dev/sdb"
        size: 0
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        - name: "ens4f1"
          macAddress: "40:A6:B7:88:84:5C"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "active-backup"
              port:
              - "ens2f0: C4:CB:E1:B5:89:01"
              - "ens4f1: 40:A6:B7:88:84:5C"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond0.400"
            description: "Bond for data transfer"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0.400"
              id: 400
            ipv4:
              address:
                prefix-length: "24"
                ip: "10.24.36.40"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.400.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "bond0.400.400"
              destination: "0.0.0.0/0"
              next-hop-address: "10.24.36.40"
    - hostName: "turkcell.slave.com"
      role: "worker"
      bmcAddress: "172.16.180.19"
      bmcCredentialsName:
        name: "bmc-credentials-1"
      nodeLabels:
        openshift-storage: "true"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "Unknown"
        deviceName: "/dev/sdc"
        size: 0
      bootMACAddress: "40:A6:B7:88:84:5C"
      nodeNetwork:
        interfaces:
        - name: "ens3f0"
          macAddress: "90:5e:d9:00:0c:6c"
        - name: "ens3f1"
          macAddress: "90:5e:d9:00:0c:6e"
        - name: "ens4f0"
          macAddress: "9c:69:b4:65:6d:a0"
        - name: "ens4f1"
          macAddress: "9c:69:b4:65:6d:a1"
        - name: "ens4f2"
          macAddress: "9c:69:b4:65:6d:a2"
        - name: "ens4f3"
          macAddress: "9c:69:b4:65:6d:a3"
        - name: "ens5f0"
          macAddress: "90:c7:10:01:67:63"
        - name: "ens5f1"
          macAddress: "90:c7:10:01:67:64"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens3f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f2"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens4f3"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens5f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "balance-xor"
              port:
              - "ens4f1: 9c:69:b4:65:6d:a1"
              - "ens4f2: 9c:69:b4:65:6d:a2"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond1"
            description: ""
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond1"
              id: 100
            ipv4:
              address:
                prefix-length: "24"
                ip: "10.24.35.40"
              enabled: true
            ipv6:
              enabled: false
            name: "bond1.100"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "1.1.1.1"
          routes:
            config:
            - next-hop-interface: ""
              destination: "0.0.0.0/0"
              next-hop-address: ""
