---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "sam-name"
  namespace: "sam-001"
spec:
  baseDomain: "sam-domain.com"
  clusterImageSetNameRef: "sam-image-001"
  sshPublicKey: "samdslfjsdkjfklsdjfkjsdklfsdfks"
  pullSecretRef:
    name: "sam-secret"
  clusters:
  - clusterName: "sam-name"
    extraManifestPath: "/sam/path"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "sam-extra.yaml"
    networkType: "OVNKubernetes"
    clusterLabels: {}
    clusterNetwork:
    - cidr: "192.168.1.0/26"
      hostPrefix: 24
    machineNetwork:
    - cidr: "192.168.1.0/26"
    apiVIP: "192.168.1.26"
    ingressVIP: "192.168.1.26"
    serviceNetwork:
    - "172.34.23.26.26"
    - "172.34.23.26.27"
    - "172.34.23.26.28"
    additionalNTPSources:
    - "172.34.23.35.35"
    - "172.34.23.35.36"
    nodes:
    - hostName: "sam-hostname"
      role: "master"
      bmcAddress: "sam-bare-address"
      bmcCredentialsName:
        name: "sam-bare-credentails"
      nodeLabels:
        openshift-storage: "true"
      bootMode: "legacy"
      rootDeviceHints:
        vendor: "Micron"
        deviceName: "sam-device name"
        size: 2626
      bootMACAddress: "40:A6:B7:88:84:26"
      nodeNetwork:
        interfaces: []
        config:
          interfaces:
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "balance-xor"
              port:
              - "sam-2"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "sam-bond"
            description: "sam transfer"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond"
              id: 2
            ipv4:
              address:
                prefix-length: "26"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond.2"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond"
              id: 3
            ipv4:
              address:
                prefix-length: "27"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond.3"
            state: "up"
            type: "vlan"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "broadcast"
              port:
              - "sam"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "sam-bond 1"
            description: "sam transfer 2"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond 1"
              id: 2
            ipv4:
              address:
                prefix-length: "26"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond 1.2"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond 1"
              id: 3
            ipv4:
              address:
                prefix-length: "27"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond 1.3"
            state: "up"
            type: "vlan"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "sam-bond 2"
            description: "sadasdas"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond 2"
              id: 2
            ipv4:
              address:
                prefix-length: "26"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond 2.2"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "sam-bond 2"
              id: 3
            ipv4:
              address:
                prefix-length: "27"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "sam-bond 2.3"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "26.26.26.26"
          routes:
            config:
            - next-hop-interface: "sam-bond 2.3"
              destination: "0.0.0.0/0"
              next-hop-address: "192.168.1.1"
