---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "dsfsdfdsf"
  namespace: "sdfdsf"
spec:
  baseDomain: "turkcell.ts"
  clusterImageSetNameRef: "sada"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ..."
  pullSecretRef:
    name: "default-secret"
  clusters:
  - clusterName: "dsfsdfdsf"
    extraManifestPath: "asdasdasd"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "sdfdsfds"
    networkType: "OVNKubernetes"
    clusterLabels:
      label1: "fdsfsdfsdf"
    clusterNetwork:
    - cidr: "103.168.1.0/3"
      hostPrefix: 24
    machineNetwork:
    - cidr: "103.168.1.0/3"
    apiVIP: "10.10.10.10"
    ingressVIP: "10.10.10.10"
    serviceNetwork:
    - "172.30.0.0/16"
    additionalNTPSources:
    - "pool.ntp.org"
    nodes:
    - hostName: "node-1.example.com"
      role: "worker"
      bmcAddress: "/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: "default-credentials"
      nodeLabels:
        role: "worker"
      bootMode: "UEFI"
      rootDeviceHints:
        vendor: "Dell"
        deviceName: "/dev/sda"
        size: 500
      bootMACAddress: "00:00:00:00:00:00"
      nodeNetwork:
        interfaces:
        - name: "eth0"
          macAddress: "00:00:00:00:00:00"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "eth0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0"
            description: "Bond interface 0"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 100
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.100"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 100
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.100"
            state: "up"
            type: "vlan"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0"
            description: "Bond interface 0"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 100
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.100"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 100
            ipv4:
              address:
                prefix-length: "24"
                ip: "192.168.1.1"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.100"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "eth0"
              destination: "0.0.0.0/0"
              next-hop-address: "192.168.1.1"
